### ISSUE TITLE
Bug on starting

### ISSUE THREAD

**Issue by lynhoff** [ThatsLiamS/autoMod#13]
Error:
`undefined`
undefined
^

SyntaxError: unexpected token u in JSON at position 0
          At JSON.parse (<anonymous>)
          At Object.<anonymous> (/home/container/bot.js:14:62)

Code:
`const admin = require('firebase-admin');
admin.initializeApp({ credential: admin.credential.cert(JSON.parse(process.env['Database'])) });
const firestore = `admin.firestore();`

**Comment by lynhoff** [comment]
![Screenshot_20220116-093937_Chrome](https://user-images.githubusercontent.com/97827006/149653919-cd6043e5-be8b-4237-8cb6-4c37c2aedb30.jpg)
![Screenshot_20220116-100811_Chrome](https://user-images.githubusercontent.com/97827006/149653939-9e58c750-4425-4469-8d16-15bf4564cf3d.jpg)

**Comment by Criticalcarpet** [comment]
Please... This is not the right way to set-up.
I assume you don't know the basics of firebase-admin sdk.
You are missing the Database env in your `.env` file.

Please refer  the docs : https://firebase.google.com/docs/admin/setup

**Comment by ThatsLiamS** [comment]
As a rule of thumb, we will not assist you with self hosting matter. 

However as Critical Carpet has explained, you failed to fill in the .env file which the Firebase SDK object.
